include:
  - remote: "https://raw.githubusercontent.com/sparkfabrik/spark-k8s-deployer/master/templates/.gitlab-ci-template.yml"
  - remote: "https://raw.githubusercontent.com/sparkfabrik/spark-k8s-deployer/master/templates/jobs/enable-buildx.yml"

variables:
  REGISTRY: europe-west1-docker.pkg.dev
  IMAGE_NAME: registry.loc/namespace
  IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
  CACHE_TAG: cache-${IMAGE_TAG}

build:
  before_script:
     - !reference [.enable-buildx, before_script]
  script: |
    docker buildx build --push --platform "linux/amd64,linux/arm64" \
    --cache-to type=registry,ref=${REGISTRY}/${IMAGE_NAME}:${CACHE_TAG},mode=max \
    --cache-from type=registry,ref=${REGISTRY}/${IMAGE_NAME}:${CACHE_TAG} \
    -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} .

