kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-${CI_PROJECT_ID}-developer
  namespace: ${KUBE_NAMESPACE}
  labels:
    purpose: dev-team-namespace-access
rules:
  - apiGroups: [ "", "extensions", "apps", "secrets", "networking", "rbac", "batch" ]
    resources: [ "deployments", "deployments/scale", "replicasets", "pods", "pods/log", "pods/exec", "configmaps", "events", "pods/portforward", "secrets", "services", "serviceaccounts", "jobs", "cronjobs", "persistentvolumeclaims", "statefulsets"]
    verbs: [ "*" ]
  - apiGroups: [ "autoscaling" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingresses/status"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "roles"]
    verbs: ["*"]
