# To use this template in your project, you must include it:
#
#   include:
#     - remote: 'https://raw.githubusercontent.com/sparkfabrik/spark-k8s-deployer/master/templates/.gitlab-ci-downstream-trigger.yml'
#
# You need to define the following enviroment variable:
#
#   - AUTOMATION_PROJECT_ID
#     Value: the GitLab ID of the automation project with the downstream pipeline.
#
#   - AUTOMATION_TRIGGER_TOKEN
#     Value: the access token used to access the automation repository with the downstream pipeline.
#
#   - AUTOMATION_BRANCH
#     Value: the branch of the project with the downstream pipeline you want to trigger.
#
#   - STAGE_CI_ENVIRONMENT_BASE_URL and PRODUCTION_CI_ENVIRONMENT_BASE_URL
#     Value: the urls of the two environments you want to deploy
#
include:
  - remote: 'https://raw.githubusercontent.com/sparkfabrik/spark-k8s-deployer/master/templates/.gitlab-ci-template.yml'

stages:
  - start

# Pipelines does not run on merge request events.
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(main|stage)$/'

.trigger-deploy-automation:
  stage: start
  script:
  - curl --request POST
    --form token=${AUTOMATION_TRIGGER_TOKEN} 
    --form ref=${AUTOMATION_BRANCH}
    --form "variables[CI_COMMIT_REF_SLUG]=${CI_COMMIT_REF_SLUG}"
    --form "variables[CI_PROJECT_ID]=${CI_PROJECT_ID}"
    --form "variables[CI_PROJECT_NAME]=${CI_PROJECT_NAME}"
    --form "variables[HTTPS_REPO_URL]=${CI_REPOSITORY_URL}"
    --form "variables[CI_COMMIT_SHA]=${CI_COMMIT_SHA}"
    --form "variables[PKG_DRUPAL_CI_ENVIRONMENT_BASE_URL]=${CI_ENVIRONMENT_BASE_URL}"
    --form "variables[DRUPAL_PHPQA_ENABLE]=${PHPQA_ENABLE}"
    "https://gitlab.sparkfabrik.com/api/v4/projects/${AUTOMATION_PROJECT_ID}/trigger/pipeline"

trigger stage deploy:
  extends: .trigger-deploy-automation
  variables:
    CI_ENVIRONMENT_BASE_URL: ${STAGE_CI_ENVIRONMENT_BASE_URL}
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage"'

trigger production deploy:
  extends: .trigger-deploy-automation
  variables:
    CI_ENVIRONMENT_BASE_URL: ${PRODUCTION_CI_ENVIRONMENT_BASE_URL}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
