include:
  - remote: 'https://raw.githubusercontent.com/sparkfabrik/spark-k8s-deployer/master/templates/.gitlab-ci-template.yml'

stages:
  - generate-pipeline
  - start

# Pipelines does not run on merge request events, only on commits on given branches.
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(develop|main|stage)$/'

variables:
  INSTALL_CACHE_NAME: ${CI_COMMIT_SHORT_SHA}-fs-install

install packages:
  stage: generate-pipeline
  script:
    - mkdir -p /tmp/sources
    - find ${CI_PROJECT_DIR} -mindepth 1 -maxdepth 1 -exec mv {} /tmp/sources \;
    - 'docker run -t -v ${CI_PROJECT_DIR}:/app -w /app -e COMPOSER_AUTH eu.gcr.io/spark-int-cloud-services/fs-cli:latest pkg:init pkg-init-dir ${CI_PROJECT_NAME} spark ${CI_PROJECT_ID}'
    - 'docker run -t -v ${CI_PROJECT_DIR}:/app -w /app/pkg-init-dir -e COMPOSER_AUTH eu.gcr.io/spark-int-cloud-services/fs-cli:latest pkg:require sparkfabrik/pkg_drupal'
    - find ${CI_PROJECT_DIR}/pkg-init-dir -mindepth 1 -maxdepth 1 -exec mv {} ${CI_PROJECT_DIR} \;
    - cd ${CI_PROJECT_DIR}/src/drupal && rm -rf behat.yml build.xml composer.* config features phpunit.xml reports web
    - cd ${CI_PROJECT_DIR}
    - find /tmp/sources -mindepth 1 -maxdepth 1 -exec mv {} ${CI_PROJECT_DIR}/src/drupal \;
    - sed -i "/local/d" .gitlab-ci.yml && cat .gitlab-ci.yml
    - apk add --no-cache tree && tree ${CI_PROJECT_DIR}
  cache:
    key: ${INSTALL_CACHE_NAME}
    paths: 
      - ${CI_PROJECT_DIR}
    policy: push
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/pkg/sparkfabrik/pkg_base/infrastructure/gitlab-ci.yml
      - ${CI_PROJECT_DIR}/pkg/sparkfabrik/pkg_drupal/infrastructure/gitlab-ci.yml
      - ${CI_PROJECT_DIR}/.gitlab-ci-project.yml
      
start drupal pipeline:
  stage: start
  variables:
    PHPQA_ENABLE: ${PHPQA_ENABLE}
  trigger:
    include:
      # - artifact: .gitlab-ci.yml
      #   job: install packages    
      - artifact: pkg/sparkfabrik/pkg_base/infrastructure/gitlab-ci.yml
        job: install packages
      - artifact: pkg/sparkfabrik/pkg_drupal/infrastructure/gitlab-ci.yml
        job: install packages
      - remote: https://raw.githubusercontent.com/sparkfabrik/spark-k8s-deployer/task/downstream_ci_template/templates/.gitlab-ci-dynamic-child-cache.yml
    # strategy: depend

# .trigger-deploy-automation:
#   stage: start
#   script:
#   - curl --request POST
#     --form token=${AUTOMATION_TRIGGER_TOKEN} 
#     --form ref=${AUTOMATION_BRANCH}
#     --form "variables[CI_COMMIT_REF_SLUG]=${CI_COMMIT_REF_SLUG}"
#     --form "variables[CI_PROJECT_ID]=${CI_PROJECT_ID}"
#     --form "variables[CI_PROJECT_NAME]=${CI_PROJECT_NAME}"
#     --form "variables[DRUPAL_PHPQA_ENABLE]=${PHPQA_ENABLE}"
#     --form "variables[HTTPS_REPO_URL]=${CI_REPOSITORY_URL}"
#     --form "variables[CI_COMMIT_SHA]=${CI_COMMIT_SHA}"
#     --form "variables[PKG_DRUPAL_CI_ENVIRONMENT_BASE_URL]=${CI_ENVIRONMENT_BASE_URL}"
#     "https://gitlab.sparkfabrik.com/api/v4/projects/${AUTOMATION_PROJECT_ID}/trigger/pipeline"

# trigger stage deploy:
#   extends: .trigger-deploy-automation
#   variables:
#     CI_ENVIRONMENT_BASE_URL: ${STAGE_CI_ENVIRONMENT_BASE_URL}
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "stage"'

# trigger production deploy:
#   extends: .trigger-deploy-automation
#   variables:
#     CI_ENVIRONMENT_BASE_URL: ${PRODUCTION_CI_ENVIRONMENT_BASE_URL}
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
