# This GitLab template contains all the jobs needed to deploy a Google Cloud Run application.
# You can find the official page of the service here: https://cloud.google.com/run
#
# You only need to configure some variables in order to correctly deploy your application.
# The runner must have all the required roles/permissions as described here:
# https://cloud.google.com/run/docs/reference/iam/roles#additional-configuration
#
# We have defined two deployment strategies to make it possible for the developers to deploy in two different ways:
# - manual: the last deploy job will be triggered manually from the pipeline
# - automatic: the last deploy job will be triggered automatically when after all the other jobs will have succeeded
# To configure the branches with the desired deployment strategy read the documentation below about variables (`BRANCHES_MANUAL_DEPLOYMENT` and `BRANCHES_AUTOMATIC_DEPLOYMENT`).
#
# Mandatory variables:
# - APP_NAME: the name for the application; it is used also as the name of the container image and the Google Cloud Run deployment (e.g. `my-awesome-app`)
# - GCP_PROJECT_ID: the Google Cloud project id (e.g. `my-sample-project-191923`)
#
# Optional variables:
# - GCP_REGION: the region in which the resource can be found (e.g. `europe-west1`) - Default: `europe-west1`
# - BRANCHES_MANUAL_DEPLOYMENT: regex that match the ${CI_COMMIT_REF_SLUG} for which the manual deploy job will be created (e.g. /^(develop|review)$/) - Default: /^(develop)$/
# - BRANCHES_AUTOMATIC_DEPLOYMENT: regex that match the ${CI_COMMIT_REF_SLUG} for which the automatic deploy job will be created (e.g. /^(master|main)$/) - Default: /^(master|main)$/
# - CI_REGISTRY_IMAGE_BASE_URL: the URL of the GCR docker image (e.g. `gcr.io/my-sample-project-191923`) - Default: gcr.io/${GCP_PROJECT_ID}
# - CI_REGISTRY_IMAGE_TAG: the tag for the docker image (e.g. `latest`) - Default: ${CI_COMMIT_SHORT_SHA}
# - DEPLOYMENT_SUFFIX: the suffix for the DEPLOYMENT_NAME, useful to create multiple deployment for the same application; if is left empty no suffix will be added to the DEPLOYMENT_NAME (e.g. `italian-website`) - Default:
# - PORT: the port used by the web server to listen for connections (e.g. `8080`) - Default: 80
# - SERVICE_ACCOUNT: the service account used by the application when it runs on Google Cloud Run (e.g. `my-low-privileged-service-account`) - Default: default Compute Engine service account as described here: https://cloud.google.com/run/docs/configuring/service-accounts
# - DOCKERFILE: the Dockerfile used to build the image (e.g. `Dockerfile.production`) - Default: Dockerfile
#
# Autogenerated variables: (do not configure these variables directly)
# - CI_REGISTRY_IMAGE: the full name of the docker image
# - DEPLOYMENT_NAME: the full name of the Google Cloud Run deployment
#
# The `BRANCHES_MANUAL_DEPLOYMENT` and `BRANCHES_AUTOMATIC_DEPLOYMENT` are used as regular expressions in the GitLab rule.
# You can read the related documentation here: https://docs.gitlab.com/ee/ci/jobs/job_control.html#cicd-variable-expressions

include:
  - remote: "https://raw.githubusercontent.com/sparkfabrik/spark-k8s-deployer/master/templates/.gitlab-ci-template.yml"

stages:
  - test
  - build
  - deploy

variables:
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1 # Disable all interactive prompts for gcloud (https://cloud.google.com/sdk/gcloud/reference#--quiet)
  GCP_REGION: europe-west1
  BRANCHES_MANUAL_DEPLOYMENT: "/^(develop)$/"
  BRANCHES_AUTOMATIC_DEPLOYMENT: "/^(master|main)$/"
  CI_REGISTRY_IMAGE_BASE_URL: gcr.io/${GCP_PROJECT_ID}
  CI_REGISTRY_IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
  CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE_BASE_URL}/${APP_NAME}:${CI_REGISTRY_IMAGE_TAG}
  # DEPLOYMENT_SUFFIX:
  # SERVICE_ACCOUNT:
  DEPLOYMENT_NAME: ${APP_NAME}-${CI_COMMIT_REF_SLUG}
  PORT: 80
  DOCKERFILE: Dockerfile

# Pipelines runs only for branches.
#
# This also remove duplicated detached pipeline created with a merge
# request or when adding a tag.
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

.print_vars:
  script:
    - |
      export PAD_LEN=40
      printf "\e[1mConfigured variables:\e[0m\n"
      for VAR_NAME in "APP_NAME" "GCP_PROJECT_ID" "GCP_REGION" "BRANCHES_MANUAL_DEPLOYMENT" \
        "BRANCHES_AUTOMATIC_DEPLOYMENT" "CI_REGISTRY_IMAGE_BASE_URL" "CI_REGISTRY_IMAGE_TAG" "CI_REGISTRY_IMAGE" \
        "DEPLOYMENT_SUFFIX" "DEPLOYMENT_NAME" "PORT" "SERVICE_ACCOUNT" "DOCKERFILE"; do
        printf "%-${PAD_LEN}s \e[1m%s\e[0m\n" "${VAR_NAME}" "${!VAR_NAME}"
      done

test variables:
  stage: test
  script:
    - |
      if [ -z "${APP_NAME}" ]; then
        echo -e "\e[1m\e[31mYou have to define the APP_NAME variable\e[0m"
        exit 1
      fi
    - |
      if [ -z "${GCP_PROJECT_ID}" ]; then
        echo -e "\e[1m\e[31mYou have to define the GCP_PROJECT_ID variable\e[0m"
        exit 1
      fi
    - !reference [.print_vars, script]
  rules:
    - if: "$CI_COMMIT_REF_SLUG =~ $BRANCHES_MANUAL_DEPLOYMENT || $CI_COMMIT_REF_SLUG =~ $BRANCHES_AUTOMATIC_DEPLOYMENT"

build:
  stage: build
  script:
    - docker build --build-arg PORT=${PORT} -t ${CI_REGISTRY_IMAGE} -f ${DOCKERFILE} .
    - docker push ${CI_REGISTRY_IMAGE}
  rules:
    - if: "$CI_COMMIT_REF_SLUG =~ $BRANCHES_MANUAL_DEPLOYMENT || $CI_COMMIT_REF_SLUG =~ $BRANCHES_AUTOMATIC_DEPLOYMENT"

.deploy-template:
  stage: deploy
  script:
    - !reference [.print_vars, script]
    # If the SERVICE_ACCOUNT variable is not defined, the `gcloud` command will be executed without `--service-account` option
    - |
      if [ -n "${SERVICE_ACCOUNT}" ]; then
        export SERVICE_ACCOUNT_OPT="--service-account ${SERVICE_ACCOUNT}"
      else
        export SERVICE_ACCOUNT_OPT=""
      fi
    - |
      if [ -n "${DEPLOYMENT_SUFFIX}" ]; then
        export FULL_DEPLOYMENT_NAME="${DEPLOYMENT_NAME}-${DEPLOYMENT_SUFFIX}"
      else
        export FULL_DEPLOYMENT_NAME="${DEPLOYMENT_NAME}"
      fi
    - gcloud run deploy ${FULL_DEPLOYMENT_NAME} --image=${CI_REGISTRY_IMAGE}
      --region ${GCP_REGION} --platform managed --allow-unauthenticated --project ${GCP_PROJECT_ID} --port=${PORT} ${SERVICE_ACCOUNT_OPT}
  rules:
    - if: "$CI_COMMIT_REF_SLUG =~ $BRANCHES_MANUAL_DEPLOYMENT"
      when: manual
    - if: "$CI_COMMIT_REF_SLUG =~ $BRANCHES_AUTOMATIC_DEPLOYMENT"

deploy:
  extends:
    - .deploy-template
