# This GitLab template contains all the jobs needed to deploy a Google Cloud Run application.
# You can find the official page of the service here: https://cloud.google.com/run
#
# You only need to configure some variables in order to correctly deploy your application.
# The runner must have all the required roles/permissions as described here:
# https://cloud.google.com/run/docs/reference/iam/roles#additional-configuration
#
# We have defined two deployment strategies to make it possible for the developers to deploy in two different ways:
# - manual: the last deploy job will be triggered manually from the pipeline
# - automatic: the last deploy job will be triggered automatically when after all the other jobs will have succeeded
# To configure the branches with the desired deployment strategy read the documentation below about variables (`BRANCHES_MANUAL_DEPLOYMENT` and `BRANCHES_AUTOMATIC_DEPLOYMENT`).
#
# Mandatory variables:
# - APP_NAME: the name for the application; it is used also as the name of the container image and the Google Cloud Run deployment (e.g. `my-awesome-app`)
# - GCP_PROJECT_ID: the Google Cloud project id (e.g. `my-sample-project-191923`)
#
# Optional variables:
# - GCP_REGION: the region in which the resource can be found (e.g. `europe-west1`) - Default: `europe-west1`
# - DEPLOYMENT_MAIN_BRANCH: the branch for which the deploy job will be created (e.g. `production`) - Default: `main`
# - DOCKER_IMAGE_NAME: the name for the docker image name (e.g. `my-awesome-app-main`) - Default: `${APP_NAME}-${CI_COMMIT_REF_SLUG}`
# - CI_REGISTRY_IMAGE_BASE_URL: the URL of the GCR docker image (e.g. `gcr.io/my-sample-project-191923`) - Default: gcr.io/${GCP_PROJECT_ID}
# - CI_REGISTRY_IMAGE_TAG: the tag for the docker image (e.g. `latest`) - Default: `${CI_COMMIT_SHORT_SHA}`
# - PORT: the port used by the web server to listen for connections (e.g. `8080`) - Default: `80`
# - DOCKERFILE: the Dockerfile used to build the image (e.g. `Dockerfile.production`) - Default: `Dockerfile`
# - SERVICE_ACCOUNT: the service account used by the application when it runs on Google Cloud Run (e.g. `my-low-privileged-service-account`) - Default: default Compute Engine service account as described here: https://cloud.google.com/run/docs/configuring/service-accounts
# - CLOUD_RUN_ENV_VARS: the environment variables use to deploy the application in Google Cloud Run (e.g. `SITE_LOCALE=${SITE_LOCALE},COMMIT_SLUG=${CI_COMMIT_REF_SLUG}`) - Default:
# - CLOUD_RUN_DEPLOY_RAW_OPTIONS: the raw options used to deploy the application in Google Cloud Run (e.g. `--memory 100Mi --async`) - Default:
#
# Autogenerated variables:
# - CI_REGISTRY_IMAGE: the full name of the docker image - Default: ${CI_REGISTRY_IMAGE_BASE_URL}/${DOCKER_IMAGE_NAME}:${CI_REGISTRY_IMAGE_TAG}
# - DEPLOYMENT_NAME: the name of the Google Cloud Run deployment - Default: ${APP_NAME}-${CI_COMMIT_REF_SLUG}
#
# You can override the variables generated automatically according to your needs.

include:
  - remote: "https://raw.githubusercontent.com/sparkfabrik/spark-k8s-deployer/master/templates/.gitlab-ci-template.yml"

stages:
  - test
  - build
  - deploy

variables:
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1 # Disable all interactive prompts for gcloud (https://cloud.google.com/sdk/gcloud/reference#--quiet)
  DOCKER_BUILDKIT: 1 # Docker build enhancements using Buildkit (https://docs.docker.com/develop/develop-images/build_enhancements/)
  GCP_REGION: europe-west1
  DEPLOYMENT_MAIN_BRANCH: main
  DOCKER_IMAGE_NAME: ${APP_NAME}-${CI_COMMIT_REF_SLUG}
  CI_REGISTRY_IMAGE_BASE_URL: gcr.io/${GCP_PROJECT_ID}
  CI_REGISTRY_IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
  CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE_BASE_URL}/${DOCKER_IMAGE_NAME}:${CI_REGISTRY_IMAGE_TAG}
  DEPLOYMENT_NAME: ${APP_NAME}-${CI_COMMIT_REF_SLUG}
  PORT: 80
  DOCKERFILE: Dockerfile
  # SERVICE_ACCOUNT:
  # CLOUD_RUN_ENV_VARS:
  # CLOUD_RUN_DEPLOY_RAW_OPTIONS:

# Pipelines runs only for branches.
#
# This also remove duplicated detached pipeline created with a merge
# request or when adding a tag.
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

.export_vars:
  script:
    # If the SERVICE_ACCOUNT variable is not defined, the `gcloud` command will be executed without `--service-account` option.
    - |
      if [ -n "${SERVICE_ACCOUNT}" ]; then
        export SERVICE_ACCOUNT_OPT="--service-account ${SERVICE_ACCOUNT}"
      else
        export SERVICE_ACCOUNT_OPT=""
      fi
    # If the CLOUD_RUN_ENV_VARS variable is not defined, the `gcloud` command will be executed without `--set-env-vars=` option.
    - |
      if [ -n "${CLOUD_RUN_ENV_VARS}" ]; then
        export CLOUD_RUN_ENV_VARS_OPT="--set-env-vars=${CLOUD_RUN_ENV_VARS}"
      else
        export CLOUD_RUN_ENV_VARS_OPT=""
      fi

.print_vars:
  script:
    - |
      export PAD_LEN=40
      printf "\e[1mConfigured variables:\e[0m\n"
      for VAR_NAME in "APP_NAME" "GCP_PROJECT_ID" "GCP_REGION" "DEPLOYMENT_MAIN_BRANCH" \
        "DOCKER_IMAGE_NAME" "CI_REGISTRY_IMAGE_BASE_URL" "CI_REGISTRY_IMAGE_TAG" "CI_REGISTRY_IMAGE" \
        "DEPLOYMENT_NAME" "PORT" "DOCKERFILE" "SERVICE_ACCOUNT" "SERVICE_ACCOUNT_OPT" \
        "CLOUD_RUN_ENV_VARS" "CLOUD_RUN_ENV_VARS_OPT"; do
        printf "%-${PAD_LEN}s \e[1m%s\e[0m\n" "${VAR_NAME}" "${!VAR_NAME}"
      done

.build_template:
  script:
    - docker build --build-arg PORT=${PORT} -t ${CI_REGISTRY_IMAGE} -f ${DOCKERFILE} .
    - mkdir -p ./docker-images-cache
    - docker save --output ./docker-images-cache/${DOCKER_IMAGE_NAME}.tar ${CI_REGISTRY_IMAGE}
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - docker-images-cache/

.load_and_push_template:
  script:
    - docker load --input ./docker-images-cache/${DOCKER_IMAGE_NAME}.tar
    - docker push ${CI_REGISTRY_IMAGE}
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - docker-images-cache/

.deploy_template:
  script:
    - !reference [.export_vars, script]
    - !reference [.print_vars, script]
    - !reference [.load_and_push_template, script]
    - gcloud run deploy ${DEPLOYMENT_NAME} --image=${CI_REGISTRY_IMAGE}
      --region ${GCP_REGION} --platform managed --allow-unauthenticated --project ${GCP_PROJECT_ID} --port=${PORT}
      ${SERVICE_ACCOUNT_OPT} ${CLOUD_RUN_ENV_VARS_OPT} ${CLOUD_RUN_DEPLOY_RAW_OPTIONS}
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - docker-images-cache/

test variables:
  stage: test
  script:
    - |
      if [ -z "${APP_NAME}" ]; then
        echo -e "\e[1m\e[31mYou have to define the APP_NAME variable\e[0m"
        exit 1
      fi
    - |
      if [ -z "${GCP_PROJECT_ID}" ]; then
        echo -e "\e[1m\e[31mYou have to define the GCP_PROJECT_ID variable\e[0m"
        exit 1
      fi
    - !reference [.export_vars, script]
    - !reference [.print_vars, script]

build:
  stage: build
  extends: .build_template

deploy:
  stage: deploy
  extends:
    - .deploy_template
  rules:
    - if: "$CI_COMMIT_REF_SLUG == $DEPLOYMENT_MAIN_BRANCH"
