phpqa:
  stage: qa
  before_script:
  script:
    - docker-compose build tools
    - docker-compose run --rm tools ash -lic "composer install --no-interaction --prefer-dist"
    # @TODO restore some kind of security-checker since the old one is deprecated: https://github.com/sensiolabs/security-checker.
    - docker run --rm -v ${PWD}:/app/drupal -v ${PWD}/reports:/app/reports ghcr.io/sparkfabrik/drupal-qa:latest phpqa --analyzedDirs "drupal/web/modules/custom,drupal/web/themes/custom" --tools "phpcpd:0,phpcs:0,phpmd:0,phpmetrics,phploc,pdepend,parallel-lint:0,phpstan:0"
  except:
    - master
    - releases
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - reports