# To use this template in your project, you must include it:
#
#   include:
#     - remote: 'https://raw.githubusercontent.com/sparkfabrik/spark-k8s-deployer/master/templates/gitlab-ci-template-drupal-phpqa.yml'
#
# Then add your job using the extends keyword (rembember to add a stage):
#
#   phpqa:
#     extends: .drupal-phpqa
#     stage: qa
#
# -------
#
.drupal-phpqa:
  before_script:
  image: ghcr.io/sparkfabrik/drupal-qa:latest
  script:
    - cd src/drupal
    - composer install --ignore-platform-reqs -v --no-interaction --prefer-dist --no-progress
    - phpqa --analyzedDirs "web/modules/custom,web/themes/custom" 
      --tools "phpcpd:0,phpcs:0,phpmd:0,phpmetrics,phploc,pdepend,parallel-lint:0,phpstan:0"
  except:
    - master
    - stage
    - releases
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - reports
