image: ghcr.io/sparkfabrik/spark-k8s-deployer:latest

services:
  - docker:19.03-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

before_script:
  - gcloud auth configure-docker
